### ISSUE TITLE
--to-64bit and Ubuntu

### ISSUE THREAD

**Issue by unxed** [pbkwee/distrorejuve#7]
Help says about this switch:

> Only tested so far with Debian **not Ubuntu**.

But [this article](https://blog.rimuhosting.com/2018/03/21/32-to-64-bit-distro-crossgrades/) suggests Ubuntu is supported also.

Is Ubuntu actually supported or not?

Thanks!

**Comment by unxed** [comment]
Also this switch is not mentioned in readme

**Comment by pbkwee** [comment]
Added to readme, thanks.

The 32 to 64 bit process is in beta.  It may work.  It may work on an Ubuntu distro.  

There are a lot of different cases to handle.  And running it on different setups can help find all those cases.  

I'd recommend you run the upgrade only after a full backup.  Ideally on a copy of the server you're updating vs. the original.  e.g. something like: https://blog.rimuhosting.com/2021/06/28/vm-backup-and-download/

If you wished we can look at doing the cross grade for you, as a service, per https://blog.rimuhosting.com/2021/07/12/distro-upgrade-as-a-service/  (part of that process would be updating distrorejuve where necessary to support the cross grade on your setup).
